name: RSS Update

on:
    schedule:
        # 日本時間 10, 12, 15, 20, 23時に実行 (UTCに直す)
        - cron: "0 1,3,6,11,14 * * *"
    workflow_dispatch: # 手動実行用のトリガー

jobs:
    # Run: 生成処理を行うジョブ
    run_process:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "23.4.0" # 必要なNode.jsのバージョンを指定

            - name: Install dependencies and run npm start
              run: |
                npm install
                npm start

            # 生成されたXMLファイルをアーティファクトとして保存
            - name: Save generated XML files as artifacts
              uses: actions/upload-artifact@v3
              with:
                name: generated-files
                path: ./*.xml # 実際のXMLファイルのパスを指定

    # Commit: 生成されたファイルをコミットするジョブ
    commit_files:
        needs: run_process  # run_processジョブが完了してから実行
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                ref: rss

            - name: Download generated XML files
              uses: actions/download-artifact@v3
              with:
                name: generated-files

            - name: Commit and push generated files to rss branch
              run: |
                  # 設定: GitHubユーザー情報
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  # 生成されたXMLファイルをコミット
                  git add *.xml
                  git commit -m "Add generated RSS files"
                  git push origin rss
