name: RSS Update

on:
    schedule:
        # 日本時間 10, 12, 15, 20, 23時に実行 (UTCに直す)
        - cron: "0 1,3,6,11,14 * * *"
    workflow_dispatch: # 手動実行用のトリガー

jobs:
    rss_update:
        runs-on: ubuntu-latest

        steps:
            # リポジトリのチェックアウト
            - name: Checkout repository
              uses: actions/checkout@v3

            # Node.js環境をセットアップ
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "23" # 必要なNode.jsのバージョンを指定

            # npm startの実行
            - name: Run npm start
              run: npm install && npm start

            - name: Clean untracked files
              run: git clean -fd

            # 生成されたXMLファイルを`rss`ブランチにコミット
            - name: Commit XML files to rss branch
              run: |
                  # 設定: GitHubユーザー情報
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  # rssブランチを取得・切り替え
                  if git ls-remote --heads origin rss; then
                    git fetch origin rss
                    git checkout rss
                  else
                    git checkout -b rss
                    git push --set-upstream origin rss
                  fi

                  # ファイルを追加してコミット
                  git add *.xml
                  if git diff-index --quiet HEAD; then
                    echo "No changes to commit"
                  else
                    git commit -m "Update RSS files: $(date -u)"
                    git push origin rss
                  fi
